# Generated by Django 2.0.5 on 2019-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimVendor',
            fields=[
                ('VENDOR_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('VENDOR_IND', models.CharField(max_length=500)),
                ('VENDOR', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DimVendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGENCY_DETAILS_ID', models.BigIntegerField()),
                ('POLICY_DETAILS_ID', models.BigIntegerField()),
                ('PERIOD_ID', models.BigIntegerField()),
                ('PROD_DETAILS_ID', models.BigIntegerField()),
                ('RETENTION_POLY_QTY', models.FloatField()),
                ('POLY_INFORCE_QTY', models.FloatField()),
                ('PREV_POLY_INFORCE_QTY', models.FloatField()),
                ('NB_WRTN_PREM_AMT', models.FloatField()),
                ('WRTN_PREM_AMT', models.FloatField()),
                ('PREV_WRTN_PREM_AMT', models.FloatField()),
                ('PRD_ERND_PREM_AMT', models.FloatField()),
                ('PRD_INCRD_LOSSES_AMT', models.FloatField()),
                ('RETENTION_RATIO', models.FloatField()),
                ('LOSS_RATIO', models.FloatField()),
                ('LOSS_RATIO_3YR', models.FloatField()),
                ('GROWTH_RATE_3YR', models.FloatField()),
            ],
            options={
                'db_table': 'FactInsurance',
                'managed': False,
            },
        ),
    ]
