# Generated by Django 2.0.5 on 2019-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAgencyDetails',
            fields=[
                ('AGENCY_DETAILS_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('AGENCY_ID', models.IntegerField()),
                ('PRIMARY_AGENCY_ID', models.IntegerField()),
                ('AGENCY_APPOINTMENT_YEAR', models.IntegerField()),
                ('ACTIVE_PRODUCERS', models.IntegerField()),
                ('MAX_AGE', models.IntegerField()),
                ('MIN_AGE', models.IntegerField()),
                ('PL_START_YEAR', models.IntegerField()),
                ('PL_END_YEAR', models.IntegerField()),
                ('COMMISIONS_START_YEAR', models.IntegerField()),
                ('COMMISIONS_END_YEAR', models.IntegerField()),
                ('CL_START_YEAR', models.IntegerField()),
                ('CL_END_YEAR', models.IntegerField()),
                ('ACTIVITY_NOTES_START_YEAR', models.IntegerField()),
                ('ACTIVITY_NOTES_END_YEAR', models.IntegerField()),
            ],
            options={
                'db_table': 'DimAgencyDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPeriod',
            fields=[
                ('PERIOD_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('STAT_PROFILE_DATE_YEAR', models.IntegerField()),
                ('MONTHS', models.IntegerField()),
            ],
            options={
                'db_table': 'DimPeriod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProd',
            fields=[
                ('PROD_DETAILS_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PROD_ABBR', models.CharField(max_length=500)),
                ('PROD_LINE', models.CharField(max_length=500)),
                ('STATE_ABBR', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DimProd',
                'managed': False,
            },
        ),
    ]
